# Generated by Django 5.0.4 on 2024-12-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('item', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('created', 'Создана'), ('in_delivery', 'Товар передан в доставку'), ('delivered', 'Товар доставлен')], default='created', max_length=20)),
            ],
        ),
    ]
