# Generated by Django 5.1.3 on 2024-12-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryorder',
            old_name='status',
            new_name='order_status',
        ),
    ]
